services:
  _defaults:
    autowire: true
    autoconfigure: true

    App\CustomersImporter\:
      resource: '*'
      exclude: '**/{Command,Dto,Entity}'

    App\CustomersImporter\DataProvider\ApiConf:
      class: 'App\CustomersImporter\DataProvider\ApiConf'
      arguments:
        $baseUrl: 'https://randomuser.me/api'