services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\CustomersImporter\Normalizer\SerializerFactory: ~

  GuzzleHttp\Client: ~

  app.customers_importer.serializer:
    class: Symfony\Component\Serializer\SerializerInterface
    factory: ['@App\CustomersImporter\Normalizer\SerializerFactory', 'create']

  App\CustomersImporter\:
    resource: './'
    exclude: '**/{Command,Dto}'

  App\CustomersImporter\DataProvider\ApiConf:
    class: 'App\CustomersImporter\DataProvider\ApiConf'
    bind:
      $baseUrl: 'https://randomuser.me/api'

  App\CustomersImporter\Normalizer\Normalizer:
    class: App\CustomersImporter\Normalizer\Normalizer
    bind:
      $serializer: '@app.customers_importer.serializer'

  App\CustomersImporter\Handler\CustomersImporterHandler:
    class: App\CustomersImporter\Handler\CustomersImporterHandler
    bind:
      $customersDataProvider: '@App\CustomersImporter\DataProvider\ApiCustomersDataProvider'

  App\CustomersImporter\DataProvider\ApiCustomersDataProvider:
    class: App\CustomersImporter\DataProvider\ApiCustomersDataProvider
    bind:
      $httpClient: '@GuzzleHttp\Client'
      $timeout: 2
